### ISSUE TITLE
Adding new ics file leads into crash

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/icsx5#185] opened 2023-10-06 16:17 UTC
When adding this calendar file in ICSx5 it leads into a crash, or the app just can't finish the parsing. Can someone investigate what happens here?

Tested with ICSx5 2.2-beta.1

Please rename this to .ics when adding in ICSx5:

[anonymkalender.txt](https://github.com/bitfireAT/icsx5/files/12833243/anonymkalender.txt)

Reference ticket: https://bitfire-at.zammad.com/#ticket/zoom/2562

**Comment by devvv4ever** [comment] 2023-11-18 09:49
@ArnyminerZ can you have a look at this please :)?

**Comment by ArnyminerZ** [comment] 2024-02-28 09:18
Seems to work on the latest version, the issue is still #220 though. I will close this issue

**Closed by ArnyminerZ** 2024-02-28 09:18 UTC
